[package]
name = "hydradx-runtime-fuzzer"
version = "0.3.0"
description = "Fuzzer for the HydraDX Runtime"
authors = ["GalacticCouncil"]
edition = "2021"
homepage = "https://github.com/galacticcouncil/HydraDX-fuzzers"
license = "Apache 2.0"
repository = "https://github.com/galacticcouncil/HydraDX-fuzzers"

[dependencies]
ziggy = { version = "0.8", default-features = false }
stats_alloc = "0.1.1"
serde = { version = "1.0.193", features = ["derive"] }
toml = "0.5"

hydradx-runtime = { git = "https://github.com/galacticcouncil/HydraDX-node.git", branch = "fuzz", default-features = false }
primitives = { git = "https://github.com/galacticcouncil/HydraDX-node.git", branch = "fuzz", default-features = false }
hydradx-traits = { git = "https://github.com/galacticcouncil/HydraDX-node.git", branch = "fuzz", default-features = false }
scraper = { git = "https://github.com/galacticcouncil/HydraDX-node.git", branch = "fuzz", default-features = false }
runtime-mock = { git = "https://github.com/galacticcouncil/HydraDX-node.git", branch = "fuzz", default-features = false }

codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false, features = ["derive"] }

frame-benchmarking = { git = "https://github.com/galacticcouncil/polkadot-sdk", rev = "062d92eae0f3bb9908faf2d4e241eef17368b9d3", default-features = false }
frame-support = { git = "https://github.com/galacticcouncil/polkadot-sdk", rev = "062d92eae0f3bb9908faf2d4e241eef17368b9d3", default-features = false }
frame-system = { git = "https://github.com/galacticcouncil/polkadot-sdk", rev = "062d92eae0f3bb9908faf2d4e241eef17368b9d3", default-features = false }

sp-core = { git = "https://github.com/galacticcouncil/polkadot-sdk", rev = "062d92eae0f3bb9908faf2d4e241eef17368b9d3", default-features = false }
sp-consensus-aura = { git = "https://github.com/galacticcouncil/polkadot-sdk", rev = "062d92eae0f3bb9908faf2d4e241eef17368b9d3", default-features = false }
sp-io = { git = "https://github.com/galacticcouncil/polkadot-sdk", rev = "062d92eae0f3bb9908faf2d4e241eef17368b9d3", default-features = false }
sp-runtime = { git = "https://github.com/galacticcouncil/polkadot-sdk", rev = "062d92eae0f3bb9908faf2d4e241eef17368b9d3", default-features = false }

cumulus-pallet-parachain-system = { git = "https://github.com/galacticcouncil/polkadot-sdk", rev = "062d92eae0f3bb9908faf2d4e241eef17368b9d3", default-features = false }
cumulus-primitives-core = { git = "https://github.com/galacticcouncil/polkadot-sdk", rev = "062d92eae0f3bb9908faf2d4e241eef17368b9d3", default-features = false }
cumulus-primitives-parachain-inherent = { git = "https://github.com/galacticcouncil/polkadot-sdk", rev = "062d92eae0f3bb9908faf2d4e241eef17368b9d3", default-features = false }
cumulus-test-relay-sproof-builder = { git = "https://github.com/galacticcouncil/polkadot-sdk", rev = "062d92eae0f3bb9908faf2d4e241eef17368b9d3", default-features = false }

orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "b3694e631df7f1ca16b1973122937753fcdee9d4", default-features = false }

[features]
default = ["std", "try-runtime"]
std = ["hydradx-runtime/std", "codec/std", "sp-runtime/std", "frame-support/std", "sp-consensus-aura/std"]
try-runtime = ["hydradx-runtime/try-runtime", "frame-support/try-runtime"]
